twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    #tous les formulaires générés par le site seront des formulaires bootstrap
    form_themes: ['bootstrap_4_layout.html.twig']

    # Paramètres disponibles dans toutes les vues twig
    globals:
        site_name: 'Pratic''Immo'
        google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
