vich_uploader:
    db_driver: orm

    mappings:
        logement_image:
            uri_prefix: /images/logements
            upload_destination: '%kernel.project_dir%/public/images/logements'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer