<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD7xXYXg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD7xXYXg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD7xXYXg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD7xXYXg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerD7xXYXg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'D7xXYXg',
    'container.build_id' => '6e96d25d',
    'container.build_time' => 1590675240,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD7xXYXg');
