<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEnqTA6p\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEnqTA6p/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEnqTA6p.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEnqTA6p\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEnqTA6p\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EnqTA6p',
    'container.build_id' => '1b03cd99',
    'container.build_time' => 1590741815,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEnqTA6p');
